run:
  timeout: 5m

linters:
  enable:
   - deadcode
   - errcheck
   - gosimple
   - govet
   - ineffassign
   - staticcheck
   - asciicheck
   - bidichk
   - bodyclose
   - cyclop
   - errorlint
   - funlen
   - goconst
   - goimports
   - gosec
   - noctx
   - prealloc
   - predeclared
   - revive
   - unconvert

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 15
