# when the filename matches any of the regex, the file or dir will be skipped.
skip_files:
  # .git .idea .vscode etc
  - '^\.'
  - ".drawio$"
image_types:
  - ".png"
  - ".jpg"
  - ".gif"
  - ".jpeg"
blog_platforms:
  - kind: cnblogs
    api: https://rpc.cnblogs.com/metaweblog/xxx
    blog_id: ""
    username: xxx
    app_key: xxx
